### ISSUE TITLE
New APIs: isAtom, watch/unwatch, atom((get)

### ISSUE THREAD

**Issue by oney** [pmndrs/jotai#1217]
jotai is a great and elegant library! Really love it!

I'd like to do some *fancy* things based on jotai. Is it possible to add the following new APIs (or existed)?

## isAtom
`function isAtom(value: any): boolean`: check if any value is an atom

## watch/unwatch
```js
const a = atom(1);
const unwatch = a.watch((value) => console.log(value));
unwatch();
```
Like [effector](https://effector.dev/docs/api/effector/createStore#example)

## Safe atom((get) => a value that is not an atom
```js
const a = atom(1);
const b = 2;
const c = atom(get => get(a) + get(b));
const [v] = useAtom(c);
// v === 3
```

`isAtom` and Safe `atom((get)` should be easy.
And if `watch/unwatch` is available, jotai can be used not only for React, but also any UI library like vue or angular like effector.

**Comment by dai-shi** [comment]
Hi, thanks for using jotai!

> watch/unwatch

jotai atoms are just configs and they don't hold values.
So, you can't directly read/write atoms.
It's very different from module state libs such as zustand and effector.

There has been a huge demand on it, so we implemented an experimental feature.
👉 #922 

How to use it:
```js
import { atom, Provider, unstable_createStore } from 'jotai'

const countAtom = atom(0)
const store = unstable_createStore()

const App = () => (
  <Provider unstable_createStore={() => store}>
    ...
  </Provider>
)

const unsub = store.sub(countAtom, () => {
  console.log('countAtom can be changed')
  const value = store.get(countAtom) // this can be the same value as the previous one
})
```

> isAtom/safe atom

While this might be easy, we don't plan to implement it in core, because TypeScript can almost catch misusage, and accepting any object can allow some hacks.

What you can do is to create wrapper functions:
```js
import { atom as original_atom } from 'jotai'

const ATOM = Symbol() // secret symbol

export const isAtom = (x) => x.type === ATOM

export const atom = (read, write) => {
  const safeRead = typeof read === 'function'
    ? (get) => read((a) => isAtom(a) ? get(a) : a)
    : read
  const config = original_atom(safeRead, write)
  config.type = ATOM
  return config
}
```

**Comment by oney** [comment]
Sounds great! Thank you for the answer and implementation.
