### ISSUE TITLE
Rerendering issue starting with 0.8.1

### ISSUE THREAD

**Issue by paulshen** [pmndrs/jotai#156]
It seems that Jotai rerenders all connected components, even ones that are not subscribed to changing atoms.

https://codesandbox.io/s/jotai-demo-forked-4fzwi

This issue starts with 0.8.1. It's okay with 0.8.0. If you type into the input and look at the console, you will see `Static` is rerendering.

**Comment by dai-shi** [comment]
Hi, thanks for trying. If I understand it correctly, this is what I'm aware of.
Long story short, you want to check the commit count with `useEffect` which should be something you would expect, instead of render count. (In CM=Concurrent Mode, render functions get called multiple times anyway.)

A technical note: This is to make it the lib CM-compatible without useMutableSource, which is not yet released. I know this is not necessary in Legacy Mode and it may influence the performance a little bit, but I didn't want to provide two versions. Once React finalizes useMutableSource, we will integrate it, which should avoid double rendering. Notice it calls the render function twice, it will only commit once.

**Comment by paulshen** [comment]
@dai-shi thanks for the quick reply!

Sorry I didn't make the example more clear. I was referring to `Static` rerendering when you type in the input. This doesn't happen if you change `jotai` version to `0.8.0`.

It does seem that `useEffect` does not get called inside `Static` even though it is rendering so maybe it's okay (and related to CM like you say)? Weird thing for me is that if `Static` renders something different, it does not commit the updates.

**Comment by paulshen** [comment]
If you open the [sandbox](https://codesandbox.io/s/jotai-demo-forked-4fzwi?file=/src/App.js) now and type in the input, you'll see that `Static` is rendered with `renderRef.current = 1` in `console.log`. However, this is not committed to the DOM (still renders 0).

**Comment by dai-shi** [comment]
To me it's expected, but it would only be for ones who know the internal implementation. I start regretting to add CM support too early. Let me work on a possible fix with feature detection.
