### ISSUE TITLE
RFC: jotai/devtools

### ISSUE THREAD

**Issue by dai-shi** [pmndrs/jotai#161]
@c0d3t3k is doing nice work on devtools: https://github.com/c0d3t3k/jotai-devtools

Should we have it officially? I also have been thinking that the current debugging tool is weak.

A few comments after having a glance at [the article](https://dev.to/c0d3t3k/jotai-not-exactly-redux-dev-tools-57i6):
- We already have `atom.debugLabel` so it can be used as well?
- Having a hook for each atom is an interesting idea. It might be more useful in some cases?
- On the other hand, would we want to enable devtools at the Provider level?
  - This might require an API at the core level. Or, we just need to wrap `Provider`.
- zustand/devtools doesn't depend on any external libs, so we should be able to do the same?

**Comment by c0d3t3k** [comment]
@dai_shi, thank you for reviewing [our article](https://dev.to/c0d3t3k/jotai-not-exactly-redux-dev-tools-57i6), providing feeback and possibly considering our `jotai-devtools` for official inclusion in Jotai!

Here are some of our thoughts:

- I agree `atom.debugLabel` should be able to be used as the atom name for the devtools instance by default. 
- `jotai-devtools` uses a single hook per atom in order to maintain atomicity in debugging. We used a similar approach when we created an internal debugging tool for [Focal](https://github.com/grammarly/focal) that was used in a [react-three-fiber](https://github.com/pmndrs/react-three-fiber) project we did for a client. With this methodology, one can simply add `useJotaiDevtools({ name, atom });` anywhere an atom is created/used. Additionally, using a shadow atom with `get` and `set` handlers, multiple atoms can be composed and registered as a single atom in `jotai-devtools`. 
- For the aforementioned reasons, IMHO the "one hook per atom" approach is preferable to centralizing devtools at the `Provider` level. 

As per your question regarding dependenices, here is how we use the packages imported by `jotai-devtools`:

- [`moment`](https://duckduckgo.com/?t=ffab&q=momentjs&ia=web): `moment` is used only to make timestamps for atom update events. A standard JS `Date` object could probably suffice for this purpose. This is most likely the easiest library to remove.
- [`react-use`](https://github.com/streamich/react-use): We use this library to handle the mount lifecycle event. This event triggers the connection to the ReduxDevtools Extension. You might be able to be replace this with something like `useEffect(() => { init() }, [])`.
- [`observable-hooks`](https://observable-hooks.js.org/): This library is used to manage streams of events from ReduxDevTools and Jotai atom changes. To listen to atom updates, we have a [`useObservable` hook](https://github.com/c0d3t3k/jotai-devtools/blob/99d8b4b78c2d4570f3f117a6344c644bbdfe64bf/src/JotaiDevtools.tsx#L73). This hook takes the current atom value as a dependency, submitting an event to the observable when the value changes. Simlarly, another [`useObservable` hook](https://github.com/c0d3t3k/jotai-devtools/blob/99d8b4b78c2d4570f3f117a6344c644bbdfe64bf/src/JotaiDevtools.tsx#L91) provides a stream of events from the DevTools Extension. Additionally, `useSubscription` hooks [are](https://github.com/c0d3t3k/jotai-devtools/blob/99d8b4b78c2d4570f3f117a6344c644bbdfe64bf/src/JotaiDevtools.tsx#L102) [included](https://github.com/c0d3t3k/jotai-devtools/blob/99d8b4b78c2d4570f3f117a6344c644bbdfe64bf/src/JotaiDevtools.tsx#L127) in sevetal places to handle events from the observables. This library would require the most effort to remove.

**Comment by dai-shi** [comment]
@c0d3t3k Sounds good. We still want to refine the api, but for now I have two points.

> IMHO the "one hook per atom" approach is preferable to centralizing devtools at the Provider level.

This is very good to know. Atom-level sounds good. And we already have debug value at Provider anyway.
I would like to hear others' opinions. Anyone looking at this issue?

> here is how we use the packages imported by jotai-devtools

That seems too much for me. Would you mind taking a look at zustand/middleware which has devtools?

**Comment by dai-shi** [comment]
Closed by #169 and #173.
