### ISSUE TITLE
(v2 API) Async atom with dep change won't be resolved in strict mode

### ISSUE THREAD

**Issue by SpringNyan** [pmndrs/jotai#1668]
## Summary

I created an async atom which depends on a refresh atom, and I want to refresh its value when the component is mounted. 

The expected behavior is: In non-strict mode `1` is displayed, in strict mode `2` is displayed.

But the actual behavior is: In strict mode, the atom value won't be resolved, and `pending` is always displayed.

## Link to reproduction

https://codesandbox.io/s/e2qukr?file=/src/App.js

## Addition

Seems this issue is caused by `registerCancelPromise`. In strict mode two promises are created, the first promise uses the second promise as its `continuePromise`, then the second promise uses the first promise as `continuePromise` too. As the result no one can be resolved since something like "dead-lock" happened.

**Comment by dai-shi** [comment]
Thanks for reporting.

Hmm, while it seems like a bug, it's kind of misusing useEffect. I'm not sure what we can do on our end, but at least it would be nice to mitigate it somehow.

A workaround: https://codesandbox.io/s/affectionate-sinoussi-dcd6sd

Can you reproduce the bug without React?

> the first promise uses the second promise as its continuePromise, then the second promise uses the first promise as continuePromise too.

Sounds like the issue is not limited to `useEffect`.

step 1: reproduce the bug in tests with store API (without React).
step 2: fix it.

**Comment by SpringNyan** [comment]
Yes, this issue is also happened in vanilla javascript, when we try to refresh and get the latest async atom value before the first promise resolved.

https://codesandbox.io/s/practical-shaw-grkgqg?file=/src/index.js

**Comment by dai-shi** [comment]
Thanks. I added a failing test in #1670. No clue yet how to solve it. There must be a proper way.

- [x] step 1: reproduce the bug in tests with store API (without React).
- [ ] step 2: fix it.

**Comment by dai-shi** [comment]
Finally fixed it in #1670!

- [x] step 1: reproduce the bug in tests with store API (without React).
- [x] step 2: fix it.
