### ISSUE TITLE
useBridge Hook Fails for Atoms with Custom Read/Write Handlers

### ISSUE THREAD

**Issue by c0d3t3k** [pmndrs/jotai#187]
The `useBridge` hook seems to fail with atoms that have custom read/write handlers when the atom is used in the same component where the hook is called.
This usage seems to create some sort of feedback loop causing React to throw a `Maximum Update Depth Exceeded` exception.

[CodeSandbox to Reproduce the Issue](https://codesandbox.io/s/jotai-bridge-issue-piqrj)

**Comment by dai-shi** [comment]
Looks like this has nothing to do with `useBridge`. I guess you can repro without it.

The problem is because atoms are created in render.
Here's the fixed version with useMemo.
https://codesandbox.io/s/jotai-bridge-issue-forked-6krbq?file=/src/App.tsx

Unless necessary, the recommendation is to define atoms outside render.

**Comment by c0d3t3k** [comment]
Alright, I will use `useMemo` from now on for this situation. Thanks for your time and help!
