### ISSUE TITLE
Jotai for libraries

### ISSUE THREAD

**Issue by vovacodes** [pmndrs/jotai#192]
As a library author, I want to make sure the values of the atoms my library relies upon are only updated in the `jotai.Provider`s I control and not the ones, the users of my library might add to the tree for their own purposes.

I believe we need some API in jotai to support it. The initial discussion happened [here](https://discord.com/channels/740090768164651008/752920140483526677/776731682232729621)

**Comment by dai-shi** [comment]
I'm thinking of something like this.

```js
import { createContainer } from 'jotai'

export const {
  Provider,
  atom,
  useAtom,
  useBridge,
  Bridge
} = createContainer()
```

This will require refactoring and it would take some time.

**Comment by dai-shi** [comment]
On second thought, it is not very ideal for the eco system. It doesn't allow `jotai/utils` or other extending libs.

Now, I wonder if there's an alternative idea.

**Comment by dai-shi** [comment]
Another idea.

```js
import { Provider, atom } from 'jotai'

const myScope = Symbol()

const countAtom = atom(0)
countAtom.scope = myScope

const App = () => (
  <Provider scope={myScope}>
    ...
  </Provider>
)
```

Not sure yet how easy/possible to implement this.

**Comment by Aslemammad** [comment]
@dai-shi I think the second one is a better thing, I've got another idea for the second one. For one scope( one provider) I think we can make jotai automatically finds it, or atoms without a scope, they will belong to the default and the first one. and for multiple providers, we can do these( your second idea) steps.

**Comment by dai-shi** [comment]
> For one scope( one provider) I think we can make jotai automatically finds it, or atoms without a scope, they will belong to the default and the first one.

Yeah, that's my point too. `scope` is just optional. The implementation wouldn't be very easy.

The first idea is also bad in terms of dead code elimination, so I wouldn't take it.

**Comment by youknowriad** [comment]
Hey there!

Just want to through something here. First, thank you for jotai, it's an amazing library and learned a lot from it.

For context, I work on the WordPress block editor and we have a data layer package caller `@wordpress/data` that relies mostly on Redux stores with some specifics. We faced performance issues while rendering a lot of components and we started exploring alternatives. Right now we are considering a solution based on atoms like Recoil and Jotai.

I'd have loved to be able to use Jotai directly, unfortunately, the specifics of the data module don't allow that. We need a library that is fundamentally React agnostic, and we also need something that can work in multiple registries/scopes (and that's why I'm commenting here).

I'm not sure if it's any helpful but I wanted to share this very experimental PR I'm currently working on https://github.com/WordPress/gutenberg/pull/26866 which creates that (a framework and scope agnostic alternative to Recoil and Jotai). My approach there was to use "registries" (though I like the proposed name here "scope").

**Comment by Aslemammad** [comment]
I'm thinking that it wouldn't be easy, but a great thing for the library.

**Comment by vovacodes** [comment]
The "scope" idea looks reasonable to me. A little bit of extra thing to always keep in mind that you need to set `scope` for each atom you are creating but most of the libraries probably won't need to create too many of those anyways.

**Comment by mdingena** [comment]
> We need a library that is fundamentally React agnostic,

@youknowriad @dai-shi I think Jotai would benefit from [having a vanilla bundle like Zustand](https://github.com/pmndrs/zustand#using-zustand-without-react).

**Comment by dai-shi** [comment]
> A little bit of extra thing to always keep in mind that you need to set scope for each atom you are creating but most of the libraries

@vovacodes I'm expecting a lib author to create its own wrapper, something like this:

```js
import { atom as atomOrig } from 'jotai'

const myScope = Symbol()
export atom = (read, write) => {
  const anAtom = atomOrig(read, write)
  anAtom.scope = myScope
  return anAtom
}
```

> I think Jotai would benefit from having a vanilla bundle like Zustand.

@mdingena @youknowriad Actually, it might be a good idea to keep the core code cleaner. I'm still working on refactoring core. However, the vanilla bundle might not be very useful as is, because it would be an unusual api to support React Concurrent Mode.

(tbh, I'm not so keen to provide framework-agnostic version of atom state management, just because there are already many: mobx, reatom or naive observables)

**Comment by Aslemammad** [comment]
> ```js
> import { atom as atomOrig } from 'jotai'
> 
> const myScope = Symbol()
> export atom = (read, write) => {
>   const anAtom = atomOrig(read, write)
>   anAtom.scope = myScope
>   return anAtom
> }
> ```
@dai-shi I think it's a really good demo, It's better because I agree with the way that the lib author creates a customized atom and provider because the symbol would always be unique.
