### ISSUE TITLE
React component as atom e.g. useAtom<React.ReactNode | null>(null)

### ISSUE THREAD

**Issue by cwackerfuss** [pmndrs/jotai#272]
I stumbled upon this interesting pattern for essentially "portaling" components -- you can store a react node as atom state. One use case I had in mind was a modal container that would persist even if the parent is unmounted, which could be useful if you're building a feature that allows you to, for example, switch pages while keeping a "popup" active.

I've done this in Redux with success in the past for components that should be triggerable globally (toasts, modals, etc), and it seemed to work fine.

One caveat of this is that in its most primitive form (`setFoo(<Bar baz={true}>Hi there</Bar>`), you're unable to update component props after the initial render. I'm imagining with more finagling, you could add a way to update props?

What are people's thoughts on this practice? Horrible? Good-for-nothin? Or actually completely acceptable and maybe a good idea?

**Comment by dai-shi** [comment]
Here's one of my tweets related to this topic: https://twitter.com/dai_shi/status/1340298590737063940

So, you could basically create a derived atom.

I think [cloneElement](https://reactjs.org/docs/react-api.html#cloneelement) should work too.
```js
  setFoo(prev => cloneElement(prev, { baz: true }));
```
Never tried though.

---
It's nice to see various patterns in jotai and they are good challenges.
I personally like it, but I wouldn't use it much apart from challenging the technical aspect.
It's just because I'd make atoms UI-agnostic, and let components be responsible for UI and styles.

**Comment by probprob** [comment]
Yes, Jotai is fun. Thanks a lot.

I guess this is similar:

PositionComponent is a updatable/reactive React Component.

https://github.com/probprob/probabilisticprogramming/blob/master/web/documentdemo/src/MoleculeComponentAtom.tsx

function Position({
  id,
  insertPos,
  deletePos,
}: {
  id: number;
  insertPos: (atId: number) => void;
  deletePos: (atId: number) => void;
}) {
  //hier wird der Setter für die Position geholt
  //das scheint in atomfamilyComponents nicht möglich zu sein
  const [, setPosition] = useAtom(
    atomfamilyPositions({ id: id, net: 0, vatrate: 0 })
  );
  const positionComponent: IPositionComponentInput = {
    id: id,
    setPosition,
    insertPos,
    deletePos,
  };
  return useAtomValue(atomfamilyComponents(positionComponent));
}

**Comment by dai-shi** [comment]
wow, you are using atomFamily extensively.
it looks good as you use atomFamily.remove(). 👍

**Comment by dai-shi** [comment]
Closing as resolved.
