### ISSUE TITLE
 Atom hook causes redundant re-renders with wrong atom value

### ISSUE THREAD

**Issue by kueychuj** [pmndrs/jotai#275]
@dai-shi @merisbahti , thanks for the quick fix. in (https://github.com/pmndrs/jotai/issues/273)

However, I seemed to find another problem on the re-rendering. 
In v0.12.6, using atom hook causes redundant re-renders and the first render produces wrong atom value.

**Example** ( https://codesandbox.io/s/romantic-forest-lixid?file=/src/App.tsx )
Switch from atomA to atomB will trigger two renders on ItemWithAtomHook component. (which should be one I believe)
The first render of ItemWithAtomHook produces a wrong atom value with correct atom label.

```ts
Item render:  atomA 
ItemWithAtomHook render:  atomA b 
ItemWithAtomHook render:  atomA a 
```

Edit: v0.11.3 works fine

_Originally posted by @kueychuj in https://github.com/pmndrs/jotai/issues/273#issuecomment-765599255_

**Comment by dai-shi** [comment]
Thanks for checking so quickly too.

Calling render function twice is the expected behavior. Although it's not ideal as you showed, I don't really know how to improve it to work both this and #208. So, I wish eventually if someone jumped in the code and had a better understanding, I'd be happy to discuss. Also, if we moved to useMutableSource once React releases it, it could be improved in the future version of React.

Anyway, we should check if the commit is fine. Let me wrap console.log with useEffect.
https://codesandbox.io/s/festive-dew-nbywn

```
Item render:  atomB 
ItemWithAtomHook render:  atomB 
ItemWithAtomHook render:  atomB 
```

Whoa! This _is_ unexpected for me. I can claim this one as a bug or an unexpected behavior.

The original one is not ideal, but not really a bug. It's a behavioral limitation.
Note: v0.11.3 is broken for #208 case.

---
Anyway, thanks so much for investigating this.
I'll work on the second issue later, not in a hurry.

**Comment by dai-shi** [comment]
> not in a hurry

Actually, #266 is failing possibly because of this, so this has a priority.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai/v/0.12.7

This fixed what I described in the comment. It doesn't change the behavior originally described in this issue. And, it's currently the expected behavior. (which could be improved in the far future.)
