### ISSUE TITLE
Error: uninitialized atom

### ISSUE THREAD

**Issue by dusanjovanov** [pmndrs/jotai#297]
Can you please explain what does this mean? I get this error in an async action when calling `get(derivedAtom)`.

**Comment by dai-shi** [comment]
This error is shown when derivedAtom is not initialized, which means it's not used with `useAtom` in advance to read it in `write` (= in action). I understand your confusion, but it's not in Provider at the point and can't be avoided (otherwise, return `undefined`). I know this is unfortunate, and have been working on it, but no idea to overcome this (one idea in mind is throw promise, but we as a community are not there yet.)

It would be nice if you could post a code snippet. Happy to learn the use case.

**Comment by dusanjovanov** [comment]
```tsx
const selectedViewIdAtom = atom(null)
const viewsAtom = atom([])
const selectedViewAtom = atom(get => {
return get(viewAtom).find(
    (s) => s.id=== get(selectedViewIdAtom)
  );
}) 

const loadViewsAtom = atom(null, async (get,set) => {
...
get(selectedViewAtom) // line that causes error
...
})
```

`loadViewsAtom`'s write is called in a component higher in the tree than where `useAtom`s for other atoms is called.
I hope this was clear :)

**Comment by dai-shi** [comment]
Thanks. Yeah, it would be nice to support this use case.
The reason we can't now is `selectedViewAtom` can be async, and we can't distinguish whether it's async.

Meanwhile, what you can do is:
```js
const selectedViewIdAtom = atom(null)
const viewsAtom = atom([])
const getSelectedView = get => {
  return get(viewAtom).find(
    (s) => s.id=== get(selectedViewIdAtom)
  );
} 
const selectedViewAtom = atom(getSelectedView)

const loadViewsAtom = atom(null, async (get, set) => {
  ...
  const selectedView = getSelectedView(get) // this probably works.
  ...
})
```

**Comment by dai-shi** [comment]
> (one idea in mind is throw promise, but we as a community are not there yet.)

Maybe, I should try this. Needs some investigation.

**Comment by dusanjovanov** [comment]
Yes, but I need selectedViewAtom in a component as well :`useAtom(selectedViewAtom)`

**Comment by dusanjovanov** [comment]
That actually worked, thanks!
