### ISSUE TITLE
Docs: Intro with conceptual differences with Redux, Context API, etc.

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/jotai#319]
Jumping into Jotai, it's easier for me to pick up from existing schemes and patterns that I have worked with, especially when I am migrating.

What are your thoughts on this topic, relating to introductory concepts and patterns?

**Comment by dai-shi** [comment]
Yes, we need a better introduction in docs. Suggestions are welcome.

What should it be look like? It would help be if there were something I need to fill out, or questions to answer.

**Comment by dai-shi** [comment]
## Conceptual difference from useContext+useState
If you were to use useContext+useState, you would probably require many contexts, and face some issues.
- provider hell: it's likely that your root component has many context providers, which is technically okay, and sometimes desirable each provider serves context in different subtree
- dynamic addition/deletion: adding a new context at runtime is not very nice, because you need to add a new provider and its children will be re-mounted (at least for now).

Jotai's atom resides only in one provider and each atom works like state.
So, conceptually it's like multiple useContext+useState sets in one context provider.

**Comment by sahilrajput03** [comment]
> ## Conceptual difference from useContext+useState
> If you were to use useContext+useState, you would probably require many contexts, and face some issues.
> 
> * provider hell: it's likely that your root component has many context providers, which is technically okay, and sometimes desirable each provider serves context in different subtree
> * dynamic addition/deletion: adding a new context at runtime is not very nice, because you need to add a new provider and its children will be re-mounted (at least for now).
> 
> Jotai's atom resides only in one provider and each atom works like state.
> So, conceptually it's like multiple useContext+useState sets in one context provider.

Nice explanation..!!
