### ISSUE TITLE
'The path "." is not exported by "jotai"' using esbuild

### ISSUE THREAD

**Issue by nivekithan** [pmndrs/jotai#354]
I am this error when I am trying to build using esbuild
```
  notes: [
        {
          location: {
            column: 13,
            file: 'node_modules/jotai/package.json',
            length: 1,
            line: 37,
            lineText: '  "exports": {',
            namespace: ''
          },
          text: 'The path "." is not exported by "jotai"'
        }
      ],
      text: 'Could not resolve "jotai" (mark it as external to exclude it from the bundle)'
    }
  ],
  warnings: []
}
```
 I am not really sure weather the problem is with esbuild or jotai 

you can check out that error by
```
gh repo clone nivekithan/jotai
cd jotai/demo
npm run esbuild
```

**Comment by Aslemammad** [comment]
@nivekithan Thanks, I'm researching about it.

**Comment by dai-shi** [comment]
FWIW, here's the entry in package.json.
https://github.com/pmndrs/jotai/blob/c3ae5796dabcc9802fc576433e8c1cd8c518b1c3/package.json#L18-L22

Wondering what `namespace: ''` means...

**Comment by evanw** [comment]
I'm the author of esbuild. This is happening because none of the conditions in the `"."` entry in the exports map apply in this case. Documentation about how the exports map works is here:

* https://nodejs.org/api/packages.html#packages_conditional_exports
* https://esbuild.github.io/api/#how-conditions-work

Import statements use the `import` condition, not the `module` condition. I'm curious about the reason why this was changed in https://github.com/pmndrs/jotai/commit/c6d54f72f539d193c3e7fb91b59bc1573d8badf3. I'm wondering about it in case it's relevant to esbuild's path resolution algorithm.

**Comment by Aslemammad** [comment]
Thanks, @evanw. I was researching about this, And yes, it's reasonable. Thanks for the great solution.

**Comment by dai-shi** [comment]
> Import statements use the `import` condition, not the `module` condition. I'm curious about the reason why this was changed in [c6d54f7](https://github.com/pmndrs/jotai/commit/c6d54f72f539d193c3e7fb91b59bc1573d8badf3). I'm wondering about it in case it's relevant to esbuild's path resolution algorithm.

There's a discussion behind this: https://github.com/pmndrs/jotai/pull/289#discussion_r574271494

index.module.js is not really .mjs, so I removed. But let's add it again and see how it goes.

**Comment by evanw** [comment]
It's ok to have `module`, and your rationale for having it (let people opt-in to `module` if they want to) is sound. But you might want to add a `default` condition so that your package doesn't break if no other condition applies. If you keep `module` but change `require` to `default` then you'll avoid the dual package hazard while allowing people to opt-in to `module` and also avoid this package breaking when it's imported without using `require`.

From [node's documentation](https://nodejs.org/api/packages.html#packages_conditional_exports):

> * `"default"` - the generic fallback that always matches. Can be a CommonJS or ES module file. _This condition should always come last._

Just another option to consider.

**Comment by dai-shi** [comment]
having `default` instead of `require` sounds good.

Do you know if we should put `import` for `*.module.js` built by rollup?

**Comment by evanw** [comment]
The `require` and `import` conditions are the only ones that are only active in certain situations. That is why using them causes the [dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard). All other conditions are either always active or never active, and cannot cause the dual package hazard. So by switching from `module` to `import` you being the dual package hazard back. 

The dual package hazard isn't necessarily the end of the world if you have a stateless library and don't mind your library ending up in a bundle multiple times, or if your `import` version just requires and re-exports the `require` version. Otherwise using something opt-in such as `module` sounds reasonable, as long as there is a `default` fallback.

**Comment by Aslemammad** [comment]
@evanw We deleted the require. Could you check #357?

**Comment by evanw** [comment]
You are still using `import` so you still have the dual package hazard. If you're ok with having the dual package hazard then it's ok to leave it like that.

But if you want to avoid the dual package hazard, you'll need to remove the `import`. Specifying only `module` + `types` + `default` would be an approach that lets users opt-in to the module code, that ensures there is always a fallback available, and that avoids the dual package hazard (since neither `import` nor `require` are present).

**Comment by Aslemammad** [comment]
@evanw Yea, Let me fix it again and talk with @dai-shi about it.
BTW, do you have discord because I have some questions to ask (if you don't have problem with that)?

**Comment by dai-shi** [comment]
I was aware of that issue. Was assuming esbuild users can use module build until `"module"` is supported.

okay, let's remove "import" and hope esbuild supports "module" some time soon.
(dual package hazard is actually more important, because jotai allows library usage.)

**Comment by Aslemammad** [comment]
@dai-shi I'll fix it soon.

**Comment by Aslemammad** [comment]
#359
