### ISSUE TITLE
Question around suspense for write atoms

### ISSUE THREAD

**Issue by aulneau** [pmndrs/jotai#364]
Here is a codesandbox -> https://codesandbox.io/s/amazing-night-9v1dr?file=/src/App.tsx

I'm a little confused about the suspense behavior around writable atoms. 

This example has 3 atoms:
- base data atom
- a writable "effect" atom (could be used for subscriptions) which updates the base atom
- a "final" atom that references the "effect" atom, and transitively the base data atom

My expectation is that if the final atom were to be used in either a `useAtom` or `useAtomValue` hook, it would take on the same suspense behavior as the "effect" atom.

Am I thinking about this the wrong way? I am trying to make an atom that can work on subscription based updates, which will suspend any atom that references it.

Thanks so much!

**Comment by dai-shi** [comment]
I understand your confusion and it has nothing to do with "effect".
The suspense behavior with async write is kind of limited and we don't have any best practice yet.
The way it behaves now is if you "use" the async writable atom directly, the component suspends.

So, in summary, what you observed is the expected behavior, and it's hard to make it differently, at least for now. I'm open for implementation suggestion, if someone can jump into the internals.

The easy workaround in your case is to add `useAtom(asyncAtom)` in "SuspenseBrokenAtom". Or, try "async read" instead of "async write". We did some complicated things in our `jotai/query` impl.

----
It would be nice to add something related to this in docs. So, let me keep this issue open for a while.

**Comment by dai-shi** [comment]
> It would be nice to add something related to this in docs. So, let me keep this issue open for a while.

Resolved by https://github.com/pmndrs/website/pull/78
