### ISSUE TITLE
Dynamically set values of an atomFamily

### ISSUE THREAD

**Issue by leifg** [pmndrs/jotai#387]
There is probably a different/better ways to achieve this but I wanted to model a selection dialogue using atomFamily booleans:

```
const selectedLanguages = atomFamily<string, boolean>(() => false)
```

Now, the selected languages are returned from an API which I want to keep consistent.

I'm imagine an atom that lets me pass in the id dynamically. So instead of having just a value, get something that exposes the method that looks up the value via id.

```
const Component = () => {
  allLanguages = ["de", "fr", "en"]
  [_selectedLanguages, setSelectedLanguages] = useAtomFamily(selectedLanguagesState) <= doesn't exist

  useEffect(() => {
    const selectedLanguagesFromApi = fetchLanguages()

    allLanguages.forEach((lang) => {
      if(selectedLanguagesFromApi.include(lang)) {
        setSelectedLanguages(lang, true)
      }
    })

  }, [])


  return(<Something />)
}
```

Am I thinking about this wrong?

**Comment by dai-shi** [comment]
You need to track the params to use the family on your end.

```js
const selectedLanguages = atomFamily<string, boolean>(() => false)

const availableLanguages = atom<string[]>([])

const selectedLanguagesState = atom(
  (get) => get(availableLanguages).filter((lang) => get(selectedLanguages(lang))),
  (get, set, { lang, value }) => {
    if (!get(availableLanguages).includes(lang)) {
      set(availableLanguages, [...get(availableLanguages), lang])
    }
    set(selectedLanguages(lang), value)
  }
)

const Component = () => {
  allLanguages = ["de", "fr", "en"]
  [_selectedLanguages, setSelectedLanguages] = useAtom(selectedLanguagesState)

  useEffect(() => {
    const selectedLanguagesFromApi = fetchLanguages()

    allLanguages.forEach((lang) => {
      if(selectedLanguagesFromApi.include(lang)) {
        setSelectedLanguages({ lang, value: true })
      }
    })

  }, [])


  return(<Something />)
}
```

It might be possible to consider adding `selectedLanguages.params()` feature. But, it's not reactive, so I don't think it's useful in this use case.

**Comment by leifg** [comment]
Thank you! I slightly changed how I store the data.

**Comment by HosseinAgha** [comment]
It is a very common pattern using useAtomFamily, can we turn this into a utility?

**Comment by dai-shi** [comment]
@HosseinAgha Would you elaborate it a bit? I'm not against to have a util for a common pattern, but in general I feel like there's a better way than using atomFamily.

**Comment by HosseinAgha** [comment]
We use atomFamily for storing/updating the server data. (specifically a map between entity Ids to their value)  
We need to initially get the previous data from the server and store it on atom families.  
We achieve that using a WriteOnly atom:  
```typescript
export const itemsWriteOnlyAtom = atom(
  null,
  (get, set, itemIdToValue: { [id: string]: Partial<Item> }) => {
    Object.keys(itemIdToValue).map((id) => {
      set(itemAtomFamily(id), {
        ...get(itemAtomFamily({ id })),
        ...itemIdToValue[id],
      });
    });
  },
);
```

Now we can batch initialize multiple atoms stored in an atomFamily. Other updates can happen normally in an Item related component:  

```tsx
const [item, setItem] = useAtom(itemAtomFamily(props.id));
// onChange -> probably a database request and update the item atom using setItem
```

**Comment by dai-shi** [comment]
Thanks. It looks good. Well, it's good as is to me.
To generalize this pattern is a bit hard. atomFamily is very flexible and not just `id` to atom mapping.
(In other words, the `itemsWriteOnlyAtom` is based on some domain knowledge.)

---

For a simple `id` to atom mapping, I'd use just an atom. I will write a guide about atoms-in-atom #435, and maybe that should cover the mapping use case.

That doesn't mean using atomFamily is bad. But, one thing to care with atomFamily is you need to `remove` it if the item is no longer used. (This is basically the same in the atoms-in-atom pattern, though.)

> for storing/updating the server data.

This is some use case I'm not familiar with, so there can be something missing in my mind.
If you already have `id` like from the server, I agree atomFamily is handy.

**Comment by HosseinAgha** [comment]
Thank you for the explanation.  

One small point about the TODO example.   

Sending atoms down using props does not feel good for me. It almost feels like sending a Reactive OOP-object with a getter and setter. This feels wrong in the functional reactive paradigm of React. I think the memo based atomFamilies are much more functional. Also, having a module-level (import) dependency on atoms unleashes the true power of the recoil idea (you don't have to send everything 4 levels down + tree shaking can create super optimized bundles).   

Maybe it's just me because I've never used MobX.

**Comment by dai-shi** [comment]
Thanks for the feedback. Maybe we show options and let developers choose. Atom configs are not like reactive objects. It's just a reference instead of a string key. I understand it may feel not good for someone. For me, one concern with atomFamily is it's Map based instead of WeakMap. Educating the use of `remove()` may solve it.

**Comment by dai-shi** [comment]
In summary, there's nothing wrong with using atomFamily and having another util around it is surely an option.
That said, my focus now is on atoms-in-atom pattern. We will see how #435 goes. We'd revisit how we'd show multiple patterns in docs.
For now, closing this as answered.

**Comment by Splendorr** [comment]
> You need to track the params to use the family on your end.
> 
> ```js
> const selectedLanguages = atomFamily<string, boolean>(() => false)
> 
> const availableLanguages = atom<string[]>([])
> 
> const selectedLanguagesState = atom(
>   (get) => get(availableLanguages).filter((lang) => get(selectedLanguages(lang))),
>   (get, set, { lang, value }) => {
>     if (!get(availableLanguages).includes(lang)) {
>       set(availableLanguages, [...get(availableLanguages), lang])
>     }
>     set(selectedLanguages(lang), value)
>   }
> )
> 
> const Component = () => {
>   allLanguages = ["de", "fr", "en"]
>   [_selectedLanguages, setSelectedLanguages] = useAtom(selectedLanguagesState)
> 
>   useEffect(() => {
>     const selectedLanguagesFromApi = fetchLanguages()
> 
>     allLanguages.forEach((lang) => {
>       if(selectedLanguagesFromApi.include(lang)) {
>         setSelectedLanguages({ lang, value: true })
>       }
>     })
> 
>   }, [])
> 
> 
>   return(<Something />)
> }
> ```
> 
> It might be possible to consider adding `selectedLanguages.params()` feature. But, it's not reactive, so I don't think it's useful in this use case.

@dai-shi Just a note to say this code block did more to help me understand reading/writing data with atomFamily than anything else I've found. The docs show how to set up an atomFamily, but not really how to read/write the data. I really struggled with how to write to a set of specific atoms by passing parameters, not within a child-specific component. I kept expecting to be able to more directly write the equivalent of:

```
const todoFamily = atomFamily();
todoFamily({ id: 1, text: "This works to create an entry" })
const Component = () => {
  [todos, setTodos] = useAtom(todoFamily);
  setTodos({ id: 1, text: "But this doesn't work to replace the existing text" });
}
```

Maybe with another `use` hook, could be called `useAtomFamily`. However, you can get effectively this behavior by writing a wrapper atom as you described (though I don't know think we can pass a parameter into the `get` method to have a single wrapper that can read and write to a specific member of the atomFamily). Some form of this would be great in the documentation!

Thanks for the great library, I really love it overall :)

**Comment by dai-shi** [comment]
I hope you don't misunderstand what atomFamily is.
It's just a simple Map of param and atom.

```js
// simplified code
const atomFamily = (initializeAtom) => {
  const cache = new Map();
  return (param) => {
    if (!cache.has(param)) {
      cache.set(param, initializeAtom(param));
    }
    return cache.get(param);
  };
};
```

Check this discussion: #1323 

Note that the code block in this issue is old. The API has changed.

---

> I kept expecting to be able to more directly write the equivalent of ...

It looks like the normal atom usage:
```js
const todoAtom = atom({ id: 1, text: "initial value" })
const Component = () => {
  const [todos, setTodos] = useAtom(todoAtom);
  const handleClick = () => {
    setTodos({ id: 1, text: "this works to replace the existing text" });
  }
  // ...
}
```

**Comment by Splendorr** [comment]
@dai-shi  Thanks for taking the time to reply! I may very well misunderstand atomFamily. I'm still new to thinking in Atoms. From your linked example, it seems I might be best-served with a custom derived atom to select from another atom that contains the info.

Also, if this would be better in a new issue, please move it / let me know.

But the example I provided was over-simplified from what I'm actually doing. In short, I'm creating a set of TV Channels, 1-999, which each need to store various data points (`status` in the example can equal "Vacant", "Occupied", or a few other values). The real dataset is more complex, which is why I need to generate the full set and populate it with API results. Then, a new set of channels (or, importantly, data related to one specific channel) can be retrieved, and I need to update the dataset.

Later, I'm successfully creating a derived atom to filter what's visible based on a few criteria. That's what I found most helpful in the above example. But I've omitted that from the example.

Here's a codesandbox where I tried to create the simplest version of what I'm doing. I was building against (I think) Jotai 1.4. The `createAllChannels()` function doesn't work in Jotai 1.8.1 to actually instantiate all the channels. 

https://codesandbox.io/s/laughing-visvesvaraya-pq3vht?file=/src/App.js

Given that it's a sequential set of channel numbers, I know I could probably just use an array and refer to the index. I foresee future datasets that aren't as straightforward. I guess I'm not clear on how to create a large array of similar objects, and then most efficiently read/write to a specific one. `splitAtom` is good for mapping, but doesn't seem right for working with a specific atom. `selectAtom` could derive a bunch of atoms from an original array, but again I'm not sure how to specifically change the status of channel 183. Or to just display channels 200 through 220.

Sorry if there's a fundamental concept I'm missing!

**Comment by dai-shi** [comment]
> Also, if this would be better in a new issue, please move it / let me know.

Yes, please open a [new discussion](https://github.com/pmndrs/jotai/discussions/new).
