### ISSUE TITLE
Write function with delayed call to set

### ISSUE THREAD

**Issue by marcselman** [pmndrs/jotai#389]
Hi,

I have an atom that I want to automatically be reset after a certain amount of time each time it is set.
I figured I could use a custom write function; something like this:
```javascript
const someAtom = atom(
	undefined,
	(get, set, update) => {
		set(someAtom, 'someData')
		window.setTimeout(() => set(someAtom, undefined) }, 5000)
	}
);
```
But this does not seem to work.
The second call to `set` has no effect. I suppose it has to do with the `setTimeout`.
Is there a simple way to achieve what I want?

Thanks for this library, I'm really enjoying it so far!

**Comment by dai-shi** [comment]
Oh, no! This is another regression in v0.15.3 refactor.
Repro: https://codesandbox.io/s/purple-darkness-l73o7?file=/src/App.js
If we downgrade to v0.15.2, it works.

Thanks for reporting and your usage is correct.

**Comment by dai-shi** [comment]
Okay, this is sort of an edge case.

The documented/recommended way is to use two atoms.
https://codesandbox.io/s/angry-flower-errno?file=/src/App.js
This works fine.

However, the original usage is "supported" (but not firstly recommended because we can't type properly in TS.) and **is** used in `atomWithReducer`. So, this is still a bug.

**Comment by marcselman** [comment]
Thanks! I will use the recommended way then 👍🏻
