### ISSUE TITLE
SetAtom<Update> result should be one of void or Promise<void>, not both

### ISSUE THREAD

**Issue by garrett-hopper** [pmndrs/jotai#416]
Currently, the type of `SetAtom<Update>` is
```ts
export declare type SetAtom<Update> = undefined extends Update ? (update?: Update) => void | Promise<void> : (update: Update) => void | Promise<void>;
```
When I call `useAtom`, it seems to me all the information is available to determine if the result of the write function will be a `Promise` or not.

It looks like this would require `WritableAtom` containing this information as a type parameter.

**Comment by garrett-hopper** [comment]
For now, I'm using this in order to call `.catch` on the result.
```ts
await (write(value) as Promise<void>).catch(handleError);
```

**Comment by dai-shi** [comment]
good point. 🤔

**Comment by dai-shi** [comment]
It turns out that we don't know if setAtom returns void or Promise<void> statically.
So, it would be best typing for now. If someone can dig into it (which would require the whole internals), it would be nice.

So, your workaround https://github.com/pmndrs/jotai/issues/416#issuecomment-817046190 seems good.
Alternatively, it can be:
```ts
Promise.resolve(write(value)).catch(handleError);
```

**Comment by dai-shi** [comment]
Closing as answered.
