### ISSUE TITLE
[Question] Jotai advantages over Recoil

### ISSUE THREAD

**Issue by NavidGhobadi** [pmndrs/jotai#420]
I have recently gotten familiar with Jotai and still searching for a concrete list of Jotai advantages over Recoil.
somehow wondering why there should be Jotai state manager with absolutely similar approach to Recoil. I'm sure maintainers are doing their best to improve the library more and more, but I wan't to get some idea about current and future of the library

**Comment by dai-shi** [comment]
This is a tricky question. It might be good to continue discussion instead of just answering once. I hope other people to jump in and have questions and answers.

For now, I have one technical aspect for an answer. Recoil atoms are distinguished by string keys and jotai atoms are by object references. Jotai's implementation is based on WeakMap, and data is garbage collected by JS engine. This simplifies the implementation quite a bit. This will be a difference that lasts for a long time, maybe forever.

**Comment by sandren** [comment]
A few advantages of Jotai over Recoil off the top of my head:

- Jotai has a smaller core API
- Jotai has a less boilerplate code (no string keys!)
- Jotai has a 90% smaller bundle size and is getting [_smaller_](https://bundlephobia.com/result?p=jotai@0.16.0) over time ([Recoil for comparison](https://bundlephobia.com/result?p=recoil@0.2.0))
- Jotai has a variety of official integrations for managing pieces of state with extra functionality (immer, optics, react-query, xstate, valtio, zustand, etc) and I'm sure more will be added over time
- Jotai will soon have persistence as an official util
- Jotai will soon have a nicer website 😉

There is also an [article on the topic](https://blog.logrocket.com/jotai-vs-recoil-what-are-the-differences/) with more information.

**Comment by Thisen** [comment]
I believe one of the major differences, besides all the previous mentioned, is that Jotai is TypeScript focused and there's a focus on delivering good DX in a TypeScript environment.

**Comment by ahfarmer** [comment]
I haven't tried Jotai yet - but just been pretty heavily burned by Recoil. Recoil essentially holds on to every piece of state it is every given. See these GitHub issues about memory leaks: https://github.com/facebookexperimental/Recoil/issues/1064 https://github.com/facebookexperimental/Recoil/issues/1040 https://github.com/facebookexperimental/Recoil/issues/981 https://github.com/facebookexperimental/Recoil/issues/954 

I'm enticed by Jotai's garbage collection and I'm looking to convert my Recoil project to Jotai now.

**Comment by dai-shi** [comment]
https://twitter.com/dai_shi/status/1423486220596699142

1. It's easier to learn because of the minimalistic API (only two basic APIs, no string keys)
2. It covers various use cases because of integrations like React Query, XState.
3. It's good for library use because atom scope allows to separate jotai in lib and jotai in app.
