### ISSUE TITLE
Create a bindings to the URQL GraphQL Client.

### ISSUE THREAD

**Issue by RIP21** [pmndrs/jotai#427]
Jotai is an awesome local state management library, but especially with GraphQL usually, some specialized clients are way more preferable than Redux, Jotai, Recoil etc. although to get GraphQL client's data into the Jotai sometimes could be very helpful.
A common example would be a select options that are getting fetched from the GraphQL backend. Currently, the process is pretty annoying with `useEffect` and other things to be used in order to sync them together, which are very error-prone and hard to manage on a big scale, being able to wrap certain queries or mutations into atoms to have some calculated data based on it and other goodness, etc. will be simply awesome.

https://github.com/FormidableLabs/urql

If anyone will try to do such wrapper, I guess the best people to review and consult on PRs would be the main maintainers of URQL @kitten and @JoviDeCroock

Thanks!
I wish I could contribute a PR, but I'm still in the learning phase of Jotai and URQL too, so not an expert I would like to be to start such work :)

**Comment by dai-shi** [comment]
I'm pretty interested in this. The point is if/how urql exposes non-React APIs.

I can work on it, but not immediately. So, if anyone is interested in taking it, leave a comment. Basically, one needs to understand how `atomWithQuery` in `jotai/query` is working now. (And, there would be room for improvement even in it.)

This would be called `jotai/urql`.

**Comment by kitten** [comment]
This could be interesting! I haven't quite looked at all of jotai's internals yet, but I do know that since it's close to how `useMutableSource` can be emulated and our `useQuery` implementation also is close to how `useMutableSource` can be emulated, it shouldn't be "hard" per se https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useQuery.ts

**Comment by dai-shi** [comment]
Yeah, at hook-level, what they are doing would be similar.

jotai/urql should probably directly depend on urql/core as atom-level it's no react involved. That's what we did with react-query.

using this: https://formidable.com/open-source/urql/docs/api/core/

and providing similar api like useQuery: https://formidable.com/open-source/urql/docs/api/urql/#usequery
(and eventually, useMutation and useSubscription...)

**Comment by kitten** [comment]
I suppose the next thing to figure out are unsubscriptions. If we want to create atoms for query (and subscription data) then there needs to be a way to end it. I haven't really dove into this codebase yet, but I hope that's in place;

If not though we could always see what other streams of information are universally interesting without having to have a clear stop or end event.

**Comment by dai-shi** [comment]
So I made a skeleton in #463 looking at https://formidable.com/open-source/urql/docs/api/core/
It's mostly from `jotai/query`. I'm not yet sure around Context, Operation and so on.
It's not tested at all, but would anyone like to play with it? Feedbacks are welcome.

**Comment by kitten** [comment]
@dai-shi It may take me a tad to get back into the `jotai` codebase but I'm happy to give it a quick read and try tomorrow ✌️

**Comment by dai-shi** [comment]
> One note is that I've seen client.reexecuteOperation used, but this method shouldn't be used by data/UI bindings

Good to know. Is there any way to allow user to refetch query, or should it be even disallowed?

**Comment by kitten** [comment]
@dai-shi typically we have a method or function in the bindings that just swaps out the source, so it'll call `client.executeQuery` again.

So the full logic in vue/react/preact/svelte is:

1. The user passes inputs which are typically used reactively:

```
export interface UseQueryArgs<T = any, V = object> {
  query: MaybeRef<TypedDocumentNode<T, V> | DocumentNode | string>;
  variables?: MaybeRef<V>;
  requestPolicy?: MaybeRef<RequestPolicy>;
  context?: MaybeRef<Partial<OperationContext>>;
  pause?: MaybeRef<boolean>;
}
```

The generic here from `TypedDocumentNode` is for the output. This is copied from the Vue bindings but looks the same for React minus the refs. The `requestPolicy` is an alias for the `context` property. `pause` means that nothing will happen until a `executeQuery` is called (ie an imperative update)

2. We create a request using `createRequest` from `@urql/core`. We don't diff `query` and `variables` by reference and instead memoize it based on `request.key`.

3. We watch `request.key` (or rather the memoized request), `requestPolicy`, `pause`, and `context` for changes (simple reference changes for `context` typically, except for Svelte where we also diff `context` deeply because memoizing there for the user is too hard.

4. On each change of the above we use a new `client.executeQuery` source and subscribe to it, discarding the last. Sometimes we can use a Subject and switchMap for this.

5. We also expose a way to call a function that swaps out the source dynamically, which triggers the above (4) explicitly.

**Comment by dai-shi** [comment]
Okay, so there's basically no way to refetch. Is it bad idea to use `client.query` instead of `client.executeQuery`?

**Comment by dai-shi** [comment]
56ccd10 modified based on my current understanding.

**Comment by kitten** [comment]
It's not a bad idea per se, but `createRequest` + `client.executeQuery` gives you a better way to diff sources. It allows you to avoid unnecessarily switching sources, as if you use `request.key` to diff `query` + `variables` you can avoid starting a new source when that's not needed, as it's common to create `variables` with a new object, which would otherwise trigger a change.

The way to refetch would be (across all libraries but this is slightly different) to imperatively use `executeQuery({ requestPolicy: 'network-only' })` and the likes, hence switching the source and triggering a refetch, more info here on what the usage of that looks like in the React bindings: https://formidable.com/open-source/urql/docs/basics/react-preact/#reexecuting-queries

Invoking `client.executeQuery` or `client.query` repeatedly doesn't do anything. However, if a user invokes the bindings' `execute` function twice that'd just switch the source twice, so the last call "wins", as in, there's only one source per hook at a time, or in this case, one source per atom that can be running.

**Comment by dai-shi** [comment]
The thing is we don't need to diff as it's only updated if needed. It's not like react hooks.

> Invoking client.executeQuery or client.query repeatedly doesn't do anything.

So, if paused=false, `executeQuery({ requestPolicy: 'network-only' })` doesn't do anything? I'm not still sure how imperative update works (like how I should get the result), but other than that, it feels good.

**Comment by kitten** [comment]
@dai-shi oh sorry! I misunderstood the question. If you only allow imperative updates then you won't need pause indeed? I suppose a user could then implement that themselves.

So, if I don't misunderstand then you only need to handle changes to the inputs as, when the user changes the `requestPolicy` that's sufficient to alter how data is refetched.

**Comment by dai-shi** [comment]
Hm? I didn't mean to only allow imperative updates.
Oh, my misunderstanding was the subscription of query is one shot only. Let me use `toPromise` which simplifies quite a bit.

**Comment by kitten** [comment]
I think a subscribe leading to a `set` would probably be sufficient? A promise wouldn't reflect future results when the cache updates or a refresh occurs. I guess the only remaining question then is whether an atom can be "destroyed" i.e. whether it can unsubscribe when the atom isn't in use anymore?

**Comment by dai-shi** [comment]
Hm, then what I thought I misunderstood was misunderstanding.

> A promise wouldn't reflect future results when the cache updates or a refresh occurs.

So, it's not one-shot. It can update results multiple times for `client.query`.

> I guess the only remaining question then is whether an atom can be "destroyed" i.e. whether it can unsubscribe when the atom isn't in use anymore?

So, we should use subscription and destory it on unmount. My previous commits did it.

I'm not familiar with wonka, but it is recommended to use, right? It would require another peer dependency.

**Comment by kitten** [comment]
@dai-shi Yea, I did just realise that this is all in one package, so `@urql/core` and `wonka` would become optional dependencies. That said, `@urql/core` (and other bindings) always depend on `wonka` so it should be available once `@urql/core` is.

Ok, I guess that means we're in-between two "working but almost there" kind of solutions? 🤔 Sorry about the misunderstandings! 😞 I left some comments on this commit to point out the three remaining things: https://github.com/pmndrs/jotai/commit/56ccd1023fd1312a94052fea6bc52e67162b5d86

I spotted that the atom should expose the entire `OperationResult<Data, Variables>` object as a result, that the generics are slightly different than how we'd set them up for other bindings, and lastly, if we revert to `pipe(client.query(...), subscribe(...))` and bring back the `unsub` logic (rather than only `toPromise`) then updates will be taken care of 🙌

**Comment by dai-shi** [comment]
I wish `@urql/core` re-export `wonka` api, because otherwise library consumers have to install both optional peer dependencies (especially for strict bundlers like yarn2).

Yeah, seems like we are almost there. Let me add some comments in the commit.

**Comment by kitten** [comment]
From my perspective it is pretty agnostic until you hit `subscribe`, so I think we should expose `subscribe` alongside `toPromise` but I'm not too sure about either yet. To be completely honest, we were very focused on bindings usages, so we haven't gotten quite that far yet 🤔

**Comment by dai-shi** [comment]
Yeah, for now it's fine. It's kind of specific bundling issue for `jotai/urql`. (In docs, we need to educate users to install `@urql/core` and `wonka`.)

**Comment by dai-shi** [comment]
Oh, `extensions` are something returned by server... 🤔

**Comment by dai-shi** [comment]
Hello folks, here's a small example:
https://codesandbox.io/s/react-typescript-forked-d9zkq?file=/src/App.tsx

Two notes:
- Initializing clientAtom is tricky and doesn't work in provider-less mode
- Is there a better way to create TypedDocumentNode in codesandbox?

**Comment by dai-shi** [comment]
Updated version: https://codesandbox.io/s/react-typescript-forked-yqboc?file=/src/App.tsx

> Initializing clientAtom is tricky and doesn't work in provider-less mode

This is resolved.

**Comment by dai-shi** [comment]
Updated version: https://codesandbox.io/s/react-typescript-forked-3bbyf?file=/src/App.tsx

> Is there a better way to create TypedDocumentNode in codesandbox?

Fixed.

**Comment by dai-shi** [comment]
Here's updated demo with https://trygql.formidable.dev/.
https://codesandbox.io/s/react-typescript-forked-zujf6?file=/src/App.tsx

**Comment by RIP21** [comment]
Wuuuuuut! Thank you very much!

How would rate its completion? Fully done, or good enough to try but rather mixed usage of original bindings + this atom when some calculated atoms based on fetched data is needed?

@kitten what's your thoughts about this implementation if any?

Unfortunately i don't have a real code base that is using URQL now to play with it and give feedback, but just curious for future projects.

**Comment by kitten** [comment]
@RIP21 I'd say it's at any given point each of our newer bindings started out at too. We'll have to see whether all API details hold up and whether it handles all edge cases. I'll see whether I find some time to port some of our examples to it, which should help
