### ISSUE TITLE
Does this lib support RN?

### ISSUE THREAD

**Issue by williamtran29** [pmndrs/jotai#43]
hi
I'm curious. Can I use Jotai with React Native?

Thanks

**Comment by dai-shi** [comment]
Yes, I suppose so. There's nothing react-dom specific.

**Comment by williamtran29** [comment]
awesome, thanks!

**Comment by dai-shi** [comment]
I wish someone would try with RN and share their experiences.

**Comment by italodeandra** [comment]
Hi,

I tested on React Native (using Expo) and its working fine.
You can check here: https://snack.expo.io/@italoandrade/jotai-rn-example

I also tested on Nextjs but weirdly it doesn't work because of "useLayoutEffect" when it's already fixed here:
https://github.com/react-spring/jotai/blob/de300431edac274f8881dcc06841ee417075cdf4/src/useAtom.ts#L18-L22

Codesandbox: https://codesandbox.io/s/jotai-nextjs-example-7i08y

**Comment by dai-shi** [comment]
> I tested on React Native (using Expo) and its working fine.

Cool!

> I also tested on Nextjs but weirdly it doesn't work

I'll be trying with nextjs sometime soon. it's on my list. i'm a newbie. check: #15

**Comment by italodeandra** [comment]
> I'll be trying with nextjs sometime soon. it's on my list. i'm a newbie. check: #15

Oh, sorry I didn't notice this issue. You're doing a great job!

**Comment by dai-shi** [comment]
There was an issue with v0.8.0 and pre-0.8.0 without locking a dependency package. #81 
It's now fixed in v0.8.1.

**Comment by ansh** [comment]
> I wish someone would try with RN and share their experiences.

I'm building a temporary internal app using Jotai for Global State, react-query for server state, and React Native (managed with Expo) for everything else! I'll definitely let you know if you want.

**Comment by dai-shi** [comment]
@ansh Sounds good. Please report issues if you find anything. Otherwise, "it works!" comment would also help.
