### ISSUE TITLE
Setting atom with async setter doesn't work after 1.0.0

### ISSUE THREAD

**Issue by DerpyCrabs** [pmndrs/jotai#544]
I'm trying to update my app to jotai 1.0.0, but `set` inside of async setter doesn't work and components get old data.

My `atom` looks like this:
```
const networkState = atom<NetworkState, SetStateAction<NetworkState>>(
  async (_get) => {
    const data = localStorage.getItem('data')
    if (!data) {
      const data = await axios.get('http://localhost:4200/1')
      const user = await data.data
      const newState: NetworkState = {
        currentUserData: user,
        lastTimeSuccessfullyUpdated: new Date(),
      }
      localStorage.setItem('data', JSON.stringify(newState))
      return newState
    } else {
      const state = JSON.parse(data)
      return {...state, lastTimeSuccessfullyUpdated: new Date(state.lastTimeSuccessfullyUpdated)}
    }
  },
  async (get, set, setAction) => {
    let newState
    if (typeof setAction === 'function') {
      newState = setAction(get(networkState))
    } else {
      newState = setAction
    }
    localStorage.setItem('data', JSON.stringify(newState))
    set(networkState, newState)
  }
)
```
There are many `atom`'s and `focusAtom`'s that get and set `networkState` but set doesn't change value of `networkState` after update to jotai 1.0.0.

**Comment by dai-shi** [comment]
Thanks for reporting.

This pattern is now prohibited in v1.0.0. I tried to throw an error, but obviously you don't see it. This is bad in DX. (@Aslemammad would you help here? or this can't be improved because of `async` write... Not sure.)

Now, this pattern requires two atoms, and `atomWithDefault` util is provided. You can use it or do the same. Let me know if you have any issues while migrating.

**Comment by DerpyCrabs** [comment]
Thank you! `atomWithDefault` fixed my issue. [My commit with update to jotai 1.0.0](https://github.com/DerpyCrabs/proactiva/commit/b5589c1ac22634014d0b5bfba2ee3673f746d7fc)
