### ISSUE TITLE
useUpdateAtom does not trigger onMount

### ISSUE THREAD

**Issue by cxc421** [pmndrs/jotai#609]
Hi, I modified [the example of useUpdateAtom in the document](https://docs.pmnd.rs/jotai/api/utils#use-update-atom) as follows:

```ts
const countAtom = atom(0);
const customSetCountAtom = atom(
  null,
  (_get, set, update: SetStateAction<number>) => {
    // Do something ....
    set(countAtom, update);
  }
);
customSetCountAtom.onMount = (setAtom) => {
  console.log(`Trigger onMount`);
  setAtom(-1);
};

const Counter = () => {
  const [count] = useAtom(countAtom);
  return (
    <div>
      count: {count}
      (rendered: {++useRef(0).current})
    </div>
  );
};

const Controls = () => {
  const setCount = useUpdateAtom(customSetCountAtom);
  const inc = () => setCount((c) => c + 1);
  return (
    <div>
      <button onClick={inc}>+1</button>
      (rendered: {++useRef(0).current})
    </div>
  );
};
```
It seems that the onMount function of the derived atom is not triggered.  
Demo: https://codesandbox.io/s/onmount-debug-th108?file=/src/App.tsx

**Comment by dai-shi** [comment]
Oh, nice catch. I didn't realized this behavioral difference.

This came from the optimization in #332, which use atom write without using it (without mounting it).
We have two options: a) revert it, or b) keep it and educate the difference.

I think we want to keep it because using atom write without mounting is better in performance.
With option b), the example needs to use useAtom instead: https://codesandbox.io/s/onmount-debug-forked-2nt6p

**Comment by cxc421** [comment]
Yes, I totally agree with option b).  
I hope you can add these exceptions to the document when you have time. 
Thanks!

**Comment by dai-shi** [comment]
Good. I guess you have a good understanding, so feel free to file a PR to the document.
