### ISSUE TITLE
How does jotai know the exact dependents? Can we have lifescycle explained in the docs

### ISSUE THREAD

**Issue by srcspider** [pmndrs/jotai#66]
Can you please update the README with one line or small paragraph on how jotai know what the dependents are for an atom with them? ie. In the example of `const uppercaseAtom = atom(get => get(textAtom).toUpperCase())` how does it know that `textAtom` is a dependent of `uppercaseAtom` and call the callback function only if `textAtom` updates. 

_I've sadly failed to confirm after throwing a glance at the source, but I'm guessing it determines all dependents on first actual use of the atom? similar to how hooks work._ 

Lifecycle transparency is very important when building anything slightly more complex then a simple example; in particular with anything async. If you ever build a docs site a small section to it would be appreciated, since when things are actually likely to get garbage collected (if ever) is another very-good-to-know tidbit to avoid shooting oneself in the foot on more complex interactions (eg. extremely large table/dataset visualization).

You should also include a section on non-singletons (since those also can have weird problems with what/when/how) and typescript types (how the typescript types need to look for example), which I assume is something like...

```typescript
interface LocalState {
	emailAtom: Atom<string>
	messageAtom: Atom<string>
	transportAtom: Atom<{ send: () => Promise<void> }>
	// ...any other static state
}

function useInit(): LocalState {
	let local = useRef<LocalState>();
	if (local.current == undefined) {
		let emailAtom = atom("");
		let messageAtom = atom("Hello, I can not ");
		
		const transportAtom = atom((get) => {
			let email = get(emailAtom);
			let message = get(messageAtom);
	  
			return {
			  send: async () => {
				console.log("SEND", { email, message });
			  }
			};
		  });

		local.current = {
			emailAtom,
			messageAtom,
			transportAtom
			// ...any other static state
		}
	}	

	return local.current;
}

function Input({ atom }) {
	let [ text, update ] = useAtom(atom);
	return <input value={text} onChange={event => update(event.target.value)}/>
}

export function ReusableContactForm() {
	let { 
		emailAtom, messageAtom, transportAtom
	} = useInit();

	let [ transport ] = useAtom(transportAtom);

	return (
		<>
			<Input atom={emailAtom}/>
			<Input atom={messageAtom}/>
			<button onClick={() => transport.send()}>Submit</button>
		</>
	);
}
```
JS Snippet Version: https://codesandbox.io/s/jotai-demo-forked-qh3qj?file=/src/App.js

The above also illustrates how for example (because `atom` internal workings are not very well explained) how you may encounter small gochas with non-obvious explanations (not that its ever obvious when a system gets big enough). In this case why cant you just use a function as a atom value and have to use that transport pattern instead. With out clarifying these use cases its unclear if thats the correct pattern as well; if there was a way to retrieve the value with out going though the entire react dance (and limitations of hooks in conditionals) then `send` could simply be a a static function declared in the `useInit` function that simply uses the atoms declared earlier in the scope; it's not easy to figure out why that's a bad idea or cant be done or if it's actually possible just not obvious.

**Comment by dai-shi** [comment]
Hey, thanks for asking. There's many points you asked. Let me organize it. I'd appreciate you confirm if anything is missing. Basically, we need to improve docs, I suppose. I'd also need some help from someone to improve docs in general.

1. how jotai knows the dependents
2. lifecycle transparency especially with async
3. non-singleton example
4. typing atoms
5. atom internal workings

I actually hope to make the internal code more readable, having struggled with it.

**Comment by dai-shi** [comment]
It would take time to have organized docs.

Let me start writing something here, getting some feedbacks, and then create a draft.

> I'm guessing it determines all dependents on first actual use of the atom?

To begin with, let's explain this. In the current implementation, every time we invoke the "read" function, we refresh dependents.

```js
const uppercaseAtom = atom(get => get(textAtom).toUpperCase())
```

The read function is the first parameter of the atom.
Initially dependency is empty. At the first use, we run the read function, and know uppercaseAtom depends on textAtom. textAtom is the dependency of uppercaseAtom. So, add uppercaseAtom to the dependents of textAtom.
Next time, when we re-run the read function (because its dependency (=textAtom) is updated),
we build the dependency again, which is the same in this case. we then remove stale dependents and replace with the latest one.

**Comment by srcspider** [comment]
Yes that seems to be all of them. Sorry for making the question a bit
overcomplicated.

**Comment by srcspider** [comment]
> Initially dependency is empty. At the first use, we run the read function, and know uppercaseAtom depends on textAtom. textAtom is the dependency of uppercaseAtom. So, add uppercaseAtom to the dependents of textAtom.
Next time, when we re-run the read function (because its dependency (=textAtom) is updated),
we build the dependency again, which is the same in this case. we then remove stale dependents and replace with the latest one.

So then, inferring what's not said...
1. `Atom` is `( read, write, dependents )` tuple of two functions (first of which might be simplified to value, 2nd of which might be omitted) and a list of dependents.
2. list of dependents starts empty, so initially `textAtom` has no dependents (and also depends on nobody)
3. when first used in combination with `useAtom` the instance of `useAtom(uppercaseAtom)` determines that it depends on `textAtom` (via inference from running read on `uppercaseAtom` once) and adds itself (ie. the instance of `useAtom(uppercaseAtom)`, not `uppercaseAtom`) to dependents of `textAtom`. If there were multiple instances of `useAtom(uppercaseAtom)` each instance would be a unique dependant.
4. when `textAtom` runs it's update function it will tell all it's dependents to update (which is `useAtom(uppercaseAtom)` in this case)
5. finally, when `useAtom(uppercaseAtom)` reaches the end of it's life in the react lifecycle it will remove itself from the dependents of `textAtom`
6. `uppercaseAtom` gets garbage collected when its out of any in use scope (including `read` function of other atoms) and not part of any `useAtom` instance.
7. `textAtom` gets garbage collected when its out of any in use scope (including `read` function of other atoms) and not part of any `useAtom` instance.

Is this correct? Or am I interpreting the explanation wrong in some way; the "we then remove stale dependents and replace with the latest one" is a bit ambiguous.

**Comment by dai-shi** [comment]
Your comment is very helpful. In the end, we should be able to produce a doc. Let me comment one by one.

> 1. `Atom` is `( read, write, dependents )` tuple of two functions (first of which might be simplified to value, 2nd of which might be omitted) and a list of dependents.

We should distinguish atom config, atom dependents and atom value (because you also mention garbage collection.) The result of `atom()` is what I call atom config. It's a JS object, and it never changes. All changeable states reside in Provider. Provider contains atom value and atom dependents (and actually promise and error.) Note, we can have multiple Providers, and the multiple Providers can share the same atom config.

> 2. list of dependents starts empty, so initially `textAtom` has no dependents (and also depends on nobody)

Yes.

> 3. when first used in combination with `useAtom` the instance of `useAtom(uppercaseAtom)` determines that it depends on `textAtom` (via inference from running read on `uppercaseAtom` once) and adds itself (ie. the instance of `useAtom(uppercaseAtom)`, not `uppercaseAtom`) to dependents of `textAtom`.

It adds `uppercaseAtom` itself to the dependents of `textAtom`, but the dependents resides in a Provider, so not the `textAtom` itself. Otherwise, correct.

>  If there were multiple instances of `useAtom(uppercaseAtom)` each instance would be a unique dependant.

So, this is not correct.

> 4. when `textAtom` runs it's update function it will tell all it's dependents to update

Yeah, more precisely, we run `textAtom`'s "write" function, which updates one or more atoms, and then, we invoke all their dependents to by running the "write" function. This is recursive procedure.

> (which is `useAtom(uppercaseAtom)` in this case)

Just `uppercaseAtom`.

> 5. finally, when `useAtom(uppercaseAtom)` reaches the end of it's life in the react lifecycle it will remove itself from the dependents of `textAtom`

Yes, we remove both the atom value in the Provider and from the dependents (in the Provider) of `textAtom`. As `useAtom(uppercaseAtom)` can be used by multiple components, we check if all of them ends the life.

> 6. `uppercaseAtom` gets garbage collected when its out of any in use scope (including `read` function of other atoms) and not part of any `useAtom` instance.

The lifecycle of the atom config has nothing to do with `useAtom`, but it's garbage collected by JS itself. So, if the atom config is stored in useRef, it will be garbage collected after the component life is end.

> 7. `textAtom` gets garbage collected when its out of any in use scope (including `read` function of other atoms) and not part of any `useAtom` instance.

Same.

> the "we then remove stale dependents and replace with the latest one" is a bit ambiguous.

It was describing more subtle behavior. Let's say if a read function is like `(get) => get(atomA) > 0 ? get(atomB) : get(atomC)`.
if the atomA value is `0`, the dependency is atomC. When the atomA value becomes `1`, we remove the stale dependency atomC, and add a new dependency atomB.

**Comment by srcspider** [comment]
I see. Thanks for the in-depth clarification.

**Comment by dai-shi** [comment]
About atom internal workings,
I try to make it work as straightforward, but there's something to note.
- If you create a primitive atom, it will use predefined read/write functions to emulate `useState` behavior.
- If you create an atom with read/write functions, they can provide any behavior with some restrictions as follows.
- `read` function will be invoked during React render phase, so the function has to be pure. What is pure in React is described [here](https://gist.github.com/sebmarkbage/75f0838967cd003cd7f9ab938eb1958f).
- `write` function will be invoked where you called initially and in useEffect for following invocations. So, you shouldn't call `write` in render.
- When an atom is initially used with `useAtom`, it will invoke `read` function to get the initial value, this is recursive process. If an atom value exists in Provider, it will be used instead of invoking `read` function.
- Once an atom is used (and stored in Provider), it's value is only updated if its dependencies are updated (including updating directly with useAtom).
