### ISSUE TITLE
iOS 10. Syntaxerror unexpected token '{'. expected '(' to start a 'catch' target

### ISSUE THREAD

**Issue by meotimdihia** [pmndrs/jotai#720]
I  have got this error with iOS 10 and Safari. Please give me a tip on how to fix it:
`syntaxerror unexpected token ' '. expected '(' to start a 'catch' target`

My tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["DOM", "DOM.Iterable", "ESNext"]
    ...
```

![F6e0GA6 1](https://user-images.githubusercontent.com/300961/133925689-423f1e81-fb04-4496-b193-6550b8ac20f4.png)

**Comment by dai-shi** [comment]
https://caniuse.com/mdn-javascript_statements_try_catch_optional_catch_binding
Mobile Safari supports it since iOS11.3.

Our compile target is `node12` which supports optional catch binding.
Assuming we don't change it, can you configure your bunder to transpile it on your end, or use CJS build? Do you use any bundler, or just tsc?

**Comment by meotimdihia** [comment]
@dai-shi I am using Next.js and Typescript. I don't understand what do you saying. 😅
Please give me more tips.

**Comment by dai-shi** [comment]
oops, sorry about that. yeah, that's good way to go.

**Comment by meotimdihia** [comment]
@meotimdihia my app works when I use `next-transpile-module` to transpile Jotai.
I close this issue. 😀
