### ISSUE TITLE
performant "Jotai Effect"

### ISSUE THREAD

**Issue by ahfarmer** [pmndrs/jotai#750]
I've found myself creating components that have a `useEffect()` and return null. The purpose is simply to update jotai state.

For example, here is an effect I wrote that takes a "time" atom and every so often updates a "throttled time" atom, which is updated less frequently and can be used by heavy react components:

```javascript
// imagine that 'timeAtom' is updated with high frequency by some other part of the app
const timeAtom = atom(null);
const throttledTimeAtom = atom(null);
const THROTTLE_MS = 500;

function ThrottleTimeEffect() {
  const time = useAtomValue(timeAtom);
  const setThrottled = useUpdateAtom(throttledTimeAtom);
  const lastTimeRef = useRef(null);

  useEffect(() => {
    const lastTime = lastTimeRef.current;
    if (time && (!lastTime || time - lastTime > THROTTLE_MS)) {
      setThrottled(time);
      lastTimeRef.current = time;
    }
  }, [time, setThrottled]);

  return null;
}
```

This works great, but the performance is not ideal. React perf tools show this component rendering in less than 1 millisecond, but React internals are doing about 30ms more work when I turn this on vs. when I turn it off. Ideally I could do these updates without React even knowing about it.

So here's my question: is there a way to create a 'jotai effect'? Perhaps something like this:

```javascript
import { effect } from "jotai";

const destroy = effect((get, set) => {
  // automatically re-runs whenever one of my get() values changes 
  // this is similar to an atom, except that it has set(), and does not have its own value
});
```

**Comment by dai-shi** [comment]
A bit of history:
We discussed about "effect" thing in #221 before v1.
The only thing we can't obviously implement is subscription use case, so we added `onMount`.
Minimal API is our philosophy, and the full effect support like recoil is something we wanted to avoid.
So, using "useEffect() and return null" is actually canonical and recommended at this point.

Now, we are working on some refactors toward/after react 18 and the internal abstraction/implementation has changed/improved since v1.0.0 and is going to change.
Also, [jotai-jsx](https://github.com/dai-shi/jotai-jsx) is a new concept and PoC implementation, that runs jotai app without React.
Due to these changes, there might be a chance that we revisit "effect" what will cover the use case of "useEffect() and return null". This won't happen anytime soon. Ideation might start in weeks or months.

That said, the "effect" thing I have in mind doesn't solve your issue, because it's the effect invoked in useEffect. (That's special timing controlled by React. Otherwise, we can solve without new features/apis.)

> Ideally I could do these updates without React even knowing about it.

If that is the goal, it's not useEffect timing. I think this pattern might work:

```js
// useEffect + return null pattern
const countAtom = atom(0)

const CountEffect = () => {
  const [count] = useAtom(countAtom)
  useEffect(() => {
    console.log('count is committed:', count)
  }, [count])
  return null
}
```
```js
// performant pattern with write function
const baseCountAtom = atom(0) // internal atom not for export
const effectsForCountAtom = atom([]) // list of effect functions
const countAtom = atom(
  (get) => get(baseCountAtom),
  (get, set, arg) => {
    set(baseCountAtom, arg)
    get(effectsForCountAtom).forEach((fn) => fn(get, set)) // can be delayed with setTimeout
  }
)

// to illustrate one usage
const CountEffect = () => {
  const setEffectsForCount = useUpdateAtom(effectsForCountAtom)
  useEffect(() => {
    const callback = (get, set) => {
      console.log('count is committed:', get(countAtom))
    }
    setEffectsForCount(prev => [...prev, callback])
    return () => {
      setEffectsForCount(prev => prev.filter(fn => fn !== callback))
    }
  }, [])
  return null
}
```

This is the basic idea and you need to tweak it for your use case.

**Comment by dmaskasky** [comment]
https://github.com/pmndrs/jotai/issues/211#issuecomment-1759946839
