### ISSUE TITLE
Changing atom in useAtom returns previous atom's value once before returning the new atom's value

### ISSUE THREAD

**Issue by hannojg** [pmndrs/jotai#827]
### Description

When changing the atom used in a `useAtom` the return value will be once the previous atom value (updating the component etc), before changing to the new atom's value. So it causes two re-renders instead of one.

### Reproduction

A full reproduction can be seen here: https://codesandbox.io/s/jotai-useatom-issue-uo0uc?file=/src/App.js

The important code part looks like this:
```js
const atom0 = atom("atom0");
const atom1 = atom("atom1");
const atom2 = atom("atom2");
const atoms = [atom0, atom1, atom2];

export default function App() {
  const [currentAtomIndex, setCurrentAtomIndex] = useState(0);
  const rotateAtoms = () => {
    setCurrentAtomIndex((prev) => (prev + 1) % atoms.length);
  };

  const [atomValue] = useAtom(atoms[currentAtomIndex]);

  useEffect(() => {
    console.log("Atom index:", currentAtomIndex, "Atom value", atomValue);
  }, [currentAtomIndex, atomValue]);
```

As you can see, while the `currentAtomIndex` has already been changed, the atom's value on the first "run" isn't.

https://user-images.githubusercontent.com/16821682/140919447-9cc2eaa5-aa73-47a4-94bd-b11fd0b0004a.mov

**Comment by hannojg** [comment]
Interestingly this works correctly: 
https://codesandbox.io/s/jotai-useatom-issue-forked-ubcfy?file=/src/App.js:552-611

Although, if you change from:
```js
  useEffect(() => {
    console.log("Atom index:", index, "Atom value", atomValue);
  }, [atomValue]);
```

to

```
console.log("Atom index:", index, "Atom value", atomValue);
```

you can see that it actually causes two re-renders

(I am not sure whether I am lacking understanding of a fundamental react/jotai concept that explains this behavior)

**Comment by dai-shi** [comment]
Thanks for reporting.
Double renders is not a problem (expected), but double effects is unexpected.
I thought [this test](https://github.com/pmndrs/jotai/blob/b22cb5027414f3b53b1507383f473758f85b8375/tests/basic.test.tsx#L754) covers such a case, but maybe something is different.

That said, at this point, we are not sure if this is fixable, or how it behaves in React 18.
So, the best for now is to workaround with tuned deps for such behavior.
Sorry for the inconvenience.

Let me label as `bug` until we understand how this is happening, but this one is not a high priority.

**Comment by dai-shi** [comment]
@Aslemammad Are you interesting in investigating this issue?

**Comment by Aslemammad** [comment]
Let's put it in my TODO list!

**Comment by Aslemammad** [comment]
Let me write my report here about what I've found.

The updates weren't synced with the effects, so I tried to synchronize them using the #761 solution, and synchronization worked.

Even though the issue wasn't non-synced renders (maybe it's part of the issue), the problem is more about scheduling. 

https://github.com/pmndrs/jotai/blob/759ee14ecab42dce869b49d7660aac2e8ec53729/src/core/useAtom.ts#L60-L62

As you can see, forceUpdate schedules the update (queue.pending), so the next render can consume it using useReducer. This makes the issue expected, but it'd be good to provide a solution (or point out that this is an issue in React itself, which there's not a high chance in this one).

I'd like to hear your thoughts.

**Comment by dai-shi** [comment]
This is interesting. It feels like a bug in useReducer, because the first click works expected (one commit), but the second click causes dual commits. tested with #841 tests.
I think you can reproduce the weird behavior without jotai.

That said, even if it's a bug in useReducer, we'd want to fix the problem with the current version. I will add a commit to #841 for a workaround.

**Comment by dai-shi** [comment]
> It feels like a bug in useReducer,

It turns out that there was a misunderstanding of mine. I thought changing the reducer reference results in the re-evaluation, but how it behaves seems correct. So, #841 is not a workaround, but a correct solution.
